import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-switch/theme-provider';
import '@/styles/globals.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
